---

- name: Create needed folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "/opt/docker-logs/{{ fqdn }}-{{ location }}"
    - /opt/{{ fqdn }}

- name: Ensure UDP is enabled
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
  loop:
    - { regexp: '#module\(load="imudp"\)', line: 'module(load="imudp")' }
    - { regexp: '#input\(type="imudp" port="514"\)', line: 'input(type="imudp" port="514")' }
  notify: "restart_rsyslog"

- name: Get list of existing rsyslog configuration files
  ansible.builtin.find:
    paths: /etc/rsyslog.d/
    patterns: '*.conf'
  register: rsyslog_files

- name: Get list of existing rsyslog configuration files
  ansible.builtin.find:
    paths: /etc/rsyslog.d/
    patterns: "*-{{ fqdn | replace('.', '-') }}.conf"
  register: rsysfile

- name: Configure Docker Logs with incremented number
  ansible.builtin.template:
    src: "sp.conf.j2"
    dest: "/etc/rsyslog.d/{{ (rsyslog_files.files | map(attribute='path') | map('basename') | map('regex_search', '^\\d+') | select('defined') | map('int') | max | default(10)) + 1 }}-{{ fqdn | replace('.', '-') }}.conf"
    mode: "0644"
  notify: "restart_rsyslog"
  when: rsysfile['matched'] == 0

- name: Configure Docker Logs
  ansible.builtin.template:
    src: "sp.conf.j2"
    dest: "/etc/rsyslog.d/{{ ( rsysfile.files | map(attribute='path') | map('basename') | first )}}"
    mode: "0644"
  notify: "restart_rsyslog"
  when: rsysfile['matched'] == 1

- name: Configure Docker Compose
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/{{ fqdn }}/{{ item }}"
    mode: "0755"
  loop:
    - "docker-compose.yml"
    - ".env"
