---
# Tasks needed to IDEM Conf Service container

- name: Create needed folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
    - "/opt/docker-logs/{{ fqdn }}-{{ location }}"
    - /opt/{{ fqdn }}

- name: Ensure UDP is enabled
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
  loop:
    - { regexp: '#module\(load="imudp"\)', line: 'module(load="imudp")' }
    - { regexp: '#input\(type="imudp" port="514"\)', line: 'input(type="imudp" port="514")' }
  notify: Restart Rsyslog

- name: Configure Docker Logs
  ansible.builtin.template:
    src: "11-idem-sp.conf.j2"
    dest: "/etc/rsyslog.d/11-idem-{{ fqdn | replace('.', '-') }}.conf"
    mode: "0644"
  notify: Restart Rsyslog

- name: Configure Docker Compose
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/opt/{{ fqdn }}/{{ item }}"
    mode: "0755"
  loop:
    - "docker-compose.yml"
    - ".env"

- name: Login on Container Registry
  ansible.builtin.command: "docker login {{ registry_location }} -u {{ registry_user }} -p {{ registry_password }}"
  register: cmd_output # <- Registers the command output.
  changed_when: cmd_output.rc != 0 # <- Uses the return code to define when the task has changed.

- name: Run service containers
  ansible.builtin.shell: "docker compose pull ; docker compose up -d"
  args:
    chdir: /opt/{{ fqdn }}
  register: cmd_output
  changed_when: cmd_output.rc != 0
