### Variables ###

## MANDATORY VARIABLES ##

# Name of the docker image
docker_image_name: "sp.example.org"

# This is the Full Qualified Domain Name used in the Apache2 configuration
fqdn: "sp.example.org"

# These are the ports used in the Apache2 configuration, mapped in docker compose. 
http_port: 8080
https_port: 8443

# The Service Provider EntityID - e.g. "https://example.org/shibboleth"
entity_id: "https://example.org/shibboleth"

### Discovery Service and Metadata
# If you need to connect one SP with only one IdP set the REMOTE_IDP_ENTITY_ID and the REMOTE_IDP_METADATA_URL variables.
# If you need to connect to >1 IdP:
# - set the WAYF_URL if you want the WAYF. (e.g. for IDEM TEST Federation, WAYF_URL="https://wayf.idem-test.garr.it/WAYF")
# - set the EDS_ENABLED to 'true' if you want to use the Shibboleth EDS
#
# Please note that only one of the alternatives can be setted at a time.
# Please leave blank all the unused variables.
# If two or more alternatives are setted the priority is: EDS > WAYF > Single IdP
eds_enabled:

wayf_url:

remote_idp_entity_id: https://idp.example.org/idp/shibboleth
remote_idp_metadata_url: https://idp.example.org/idp/shibboleth

# These variables are used to set where the SSL certificates (and private key) are. 
# By default the certificates are on the host where the instance is running.
ssl_cert_host_location: /opt/certs
ssl_cert_location: /opt/certs

## OPTIONAL VARIABLES ##

# Name of the Container Registry where the image is uploaded. Leave blank if unused.
docker_image_location:
# Name of the SP docker image version 
docker_image_version: example

### Registry Variables
# If you don't use a registry you can leave the "registry_" variables blank.
# URL location of your registry
registry_location:
# User used to access the registry
registry_user:
# User's password. Please remember to use !valut to keep it safe!
registry_password:

# This is used to customize the name of the docker container - e.g. "local" 
location: local

# This is the ServerAdmin in the Apache2 configuration
server_admin: admin@example.org

# Passphrase used to decrypt the private keys. 
# If you already have a pair of certificates for signing and encryption, 
# you MUST protect them through encryption.
# In order to decrypt the private keys, they must be named:
# sp-signing-key-encrypted.pem and sp-encrypt-key-encrypted.pem
cert_passphrase:

# If the Chain certificate is not included in the SSL cert file, set also the ca_cert file name.
ca_cert:

# To use MDX service, set the MDX_FED_TYPE variable. 
# Possible values: idem-test, idem, edugain.
# More infos here: https://mdx.idem.garr.it
mdx_fed_type:

# This variable is part of the UI (check header, index for more).
# If you are part of IDEM/eduGAIN federation, use: "IDEM Test" or "IDEM and eduGAIN".
federation_type:

# This is used by the docker syslog logging driver.
# An UDP connection is used. Insert the IP of the syslog.
# Check docker-compose.yml.j2 for more.
syslog_ip:

# This variable is used for enabling HAProxy with Proxy Protocol when setted to "prod".
# Leave it blank if you are not using HAProxy with Proxy Protocol.
deploy_type: example

# This variable is used to define the IP range of your HAProxy instance when using the Proxy Protocol in front of the SP. 
# Leave it blank if you are not using HAProxy with Proxy Protocol.
haproxy_ip_range: