- name: Deploy IDEM SP
  hosts: #Insert the name of your RemoteHost or localhost
  become: true
  become_method: sudo
  remote_user: #Insert the SSH user name that has access to the remote vm
  roles:
    - requirements
    - setup
    #- pull
    #- run